services:
  registry:
    container_name: registry
    build:
      dockerfile: ./services/registry/Dockerfile
      context: .
    ports:
      - 3031:3031
  paper:
    container_name: paper
    build:
      dockerfile: ./services/paper/Dockerfile
      context: .
    ports:
      - 3032:3032
  member:
    container_name: member
    build:
      dockerfile: ./services/member/Dockerfile
      context: .
    ports:
      - 3033:3033
  mesh:
    container_name: mesh
    build:
      dockerfile: ./mesh/Dockerfile
      context: .
    ports:
      - 3034:4000
    links:
      - member
      - paper
      - registry
    depends_on:
      - member
      - paper
      - registry
  gateway:
    container_name: gateway
    build:
      dockerfile: ./gateway/Dockerfile
      context: .
    ports:
      - 3034:4000
    links:
      - paper
      - registry
    depends_on:
      - paper
      - registry
