serve: 
  cors:
    exposedHeaders:
      - authentication
sources:
  - name: vendor_core 
    handler:
      graphql:
        endpoint: http://localhost:3035/graphql
        operationHeaders:
          authorization: '{context.headers.authorization}'
  - name: vendor_checklist
    handler:
      graphql:
        endpoint: http://localhost:3036/graphql
        operationHeaders:
          authorization: '{context.headers.authorization}'
  - name: registries
    handler:
      graphql:
        endpoint: http://localhost:3031/graphql
        operationHeaders:
          authorization: '{context.headers.authorization}'
    transforms:
      - encapsulate:
          applyTo:
            query: true
            mutation: true
            subscription: true
      - prefix:
          value: Registry_
      - rename:
          renames:
            - from:
                type: Registry_registriesQuery
                field: products
              to:
                type: Query
                field: products
  - name: papers
    handler:
      graphql:
        endpoint: http://localhost:3032/graphql
        operationHeaders:
          authorization: '{context.headers.authorization}'
    transforms:
      - encapsulate:
          applyTo:
            query: true
            mutation: true
            subscription: true
      - prefix:
          value: Paper_
      - rename:
          renames:
            - from:
                type: Paper_papersQuery
                field: products
              to:
                type: Query
                field: products

  - name: membership
    handler:
      openapi:
        source: http://localhost:3033/api-json
        endpoint: http://localhost:3033/
        operationHeaders:
          authorization: '{context.headers.authorization}'
    transforms:
      - encapsulate:
          applyTo:
            query: true
            mutation: true
            subscription: true
      - prefix:
          value: Membership_
